# This inventory file tells Ansible where to run.
# In this case, we define 'localhost' and tell Ansible to use the 'local'
# connection plugin instead of trying to connect via SSH.

[localhost]
localhost ansible_connection=local
